<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="<?php echo base_url($header_link_1) ?>"><?php echo $header_1 ?></a></li>


                </ol>
            </div>
            <h4 class="page-title">Import and Update Question Details</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6 col-md-6 col-lg-6">
        <div class="card">
            <div class="card-body">
                <h5>Insertion for New data (kindly follow below steps while importing data)</h5>
                <ol>
                    <li>Download <b>"Insertion Template"</b> file to insert new question details.</li>
                    <li>For Question type enter <b>"MCQ"</b> for Multiple Choice Question and <b>"SCQ"</b> for Single Choice Question in "Type" Column.</li>
                    <li>For Correct option enter <b>"TRUE"</b> in "Correct" Column.</li>
                    <li>Warning: Question, Type, Option, and Correct fields are mandatory. Insertion stops from that record if any of these fields is missing.</li>
                    <br />
                </ol>
                <form class="form-inline" enctype="multipart/form-data" action="<?php echo base_url('Assessment/trainings/importNewquestionsOption'); ?>" method="post" id="submitForm"><?= csrf_field() ?>
                    <?= csrf_field() ?>
                    <div class="col-md-4"><a href="<?php echo base_url('assets/assets/uploads/insert_quiz_sample.xlsx'); ?>" target="_blank" class="btn btn-outline-info  btn-xs rounded-pill waves-effect waves-light">Insertion Template</a></div><br />
                    <div class="col-md-8">
                        <div class="mb-2">
                            <div class="input-group file">
                                <input type="file" name="file" id="file" accept=".xlsx" required>
                            </div>
                        </div>
                        <div class="mb-2">
                            <input type="hidden" name="scourse_id" value="<?php echo $scourse_id; ?>">
                            <input type="hidden" name="page_id" value="<?php echo $page_id ?>">
                            <button type="submit" class="btn btn-outline-primary waves-effect btn-sm waves-light col-md-12" id="submitButton">
                                Import New Questions Details
                            </button>
                        </div>
                    </div>
                    <?php if (isset($excelvalidation)) : ?>
                        <div class=col-12 col-sm-4>
                            <div class="alert alert-danger" role="alert">
                                <?= $excelvalidation->listErrors() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </form>

            </div>
        </div>
    </div>
    <div class="col-6 col-md-6 col-lg-6">
        <div class="card">
            <div class="card-body">
                <h5>Update Existing data (kindly follow below steps while importing data)</h5>
                <ol>
                    <li>Download <b>"Export Questions"</b> file to update existing question details.</li>
                    <li>For Question type enter <b>"MCQ"</b> for Multiple Choice Question and <b>"SCQ"</b> for Single Choice Question in "Type" Column.</li>
                    <li>For Correct option enter <b>"TRUE"</b> in "Correct" Column.</li>
                    <li>Warning : Dont Edit Grey highlighted area (Question ID's and Option ID's) in Excel, which is generated by system.</li>
                    <br />
                </ol>
                <div class="col-md-4 col-sm-4 form-group pull-right">
                    <form class="form-horizontal" action="<?php echo base_url('Assessment/trainings/export_questions_excel') ?>" method="POST"><?= csrf_field() ?>
                        <?= csrf_field() ?>
                        <input type="hidden" name="scourse_id" value="<?php echo $scourse_id; ?>">
                        <input type="hidden" name="page_id" value="<?php echo $page_id ?>">
                        <input type="hidden" name="course_name" value="<?php echo $course_name ?>">
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-danger  btn-xs rounded-pill waves-effect waves-light">Export Questions</button>
                        </div>
                    </form>

                </div><br />
                <form class="form-inline" enctype="multipart/form-data" action="<?php echo base_url('Assessment/trainings/importquestionsOption'); ?>" method="post" id="submitForm"><?= csrf_field() ?>
                    <?= csrf_field() ?>
                    <div class="col-md-8">
                        <div class="mb-2">
                            <div class="input-group file">
                                <input type="file" name="file" id="file" accept=".xlsx" required>
                            </div>
                        </div>
                        <div class="mb-2">
                            <input type="hidden" name="scourse_id" value="<?php echo $scourse_id; ?>">
                            <input type="hidden" name="page_id" value="<?php echo $page_id ?>">
                            <button type="submit" class="btn btn-outline-warning waves-effect btn-sm waves-light col-md-12" id="submitButton">
                                Update Questions Details
                            </button>
                        </div>
                    </div>
                    <?php if (isset($excelvalidation)) : ?>
                        <div class=col-12 col-sm-4>
                            <div class="alert alert-danger" role="alert">
                                <?= $excelvalidation->listErrors() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </form>
            </div>
        </div>
    </div>
</div>